### ISSUE TITLE
Album art not fully stretching over the display

### ISSUE THREAD

**Issue by Miepee** [f-leoni/lyrics2#21]
The album art seems rounded, as I can see white (depending on theme) spots in the left and right bottom corner.

**Comment by f-leoni** [comment]
Would you mind adding a screenshot? Thanks

**Comment by Miepee** [comment]
My bad, here you go.
![image](https://user-images.githubusercontent.com/38186597/230650516-0981d33c-2979-479f-8cc7-b40c6c252780.png)

Happens with every song, but some more info in case that helps
- Phone is redmi note 11 (res should be 2400x1080)
- song was Hollow: https://genius.com/Nobuo-uematsu-hollow-lyrics

**Comment by f-leoni** [comment]
Fixed in next relase: I had a rounded border for the background image
