### ISSUE TITLE
Genius not working

### ISSUE THREAD

**Issue by mxwmnn** [f-leoni/lyrics2#25]
Search results work, but if I click on a song it loads but nothing happens

**Comment by f-leoni** [comment]
This is solved in latest F-Droid release (1.0.25). Genius changed something in their web pages and I had to adapt.

**Comment by mxwmnn** [comment]
I have the latest f-droid version installed

**Comment by f-leoni** [comment]
Which Version and Build number  do you see  at the bottom of the "Info" tab?

**Comment by mxwmnn** [comment]
1.0.2
